repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args: [--max-line-length=88, "--ignore=E203,E501,W503"]


  - repo: local
    hooks:
      - id: custom-check
        name: Custom Pre-commit Check
        entry: pre-push.py
        language: python
        types: [python]
